/* Todos los intentos usan el mismo banco; solo cambia el orden. */
window.TOPICS = ['Medición, unidades y vectores','Movimiento y gráficas','Fuerzas y leyes de Newton'];
window.QUESTIONS = [
  {id:'m-sentido',topic:1,type:'choice',source:'Física I.html:1247-1267',prompt:'Para describir un vector representado con una flecha, ¿qué conjunto de características debes identificar?',choices:['Magnitud, dirección y sentido','Magnitud, dirección y unidad','Magnitud, sentido y punto de referencia','Dirección, sentido y distancia recorrida'],answer:'Magnitud, dirección y sentido',explain:'La longitud de la flecha representa la magnitud, su orientación indica la dirección y la punta muestra el sentido.'},
  {id:'m-precision',topic:1,type:'parts',source:'Física I.html:1295-1303,1733-1746',prompt:'La masa aceptada de un objeto es 3.00 kg. Al medirlo tres veces, una báscula registra 3.18 kg, 3.20 kg y 3.22 kg. Para evaluar la precisión y la exactitud, calcula la diferencia entre la medición mayor y la menor, y la diferencia entre el promedio de las tres mediciones y la masa aceptada. Escribe ambos resultados con dos decimales.',parts:[{id:'rango',label:'Diferencia entre la medición mayor y la menor',unit:'kg',answer:0.04,decimals:2},{id:'diferencia',label:'Diferencia entre el promedio y la masa aceptada',unit:'kg',answer:0.20,decimals:2}],explain:'El rango es 3.22 − 3.18 = 0.04 kg. El promedio es 3.20 kg y se separa 3.20 − 3.00 = 0.20 kg del valor aceptado. Las mediciones son cercanas entre sí, pero se alejan de la masa aceptada.'},
  {id:'m-resolucion',topic:1,type:'choice',source:'Física I.html:1313-1321',prompt:'Dos reglas tienen el mismo rango. Una está marcada cada centímetro y otra cada milímetro. ¿Cuál detecta cambios más pequeños?',choices:['La marcada cada milímetro','La marcada cada centímetro','Las dos por igual','No puede saberse sin medir un objeto'],answer:'La marcada cada milímetro',explain:'La resolución es el cambio mínimo detectable; un milímetro es menor que un centímetro.'},
  {id:'m-promedio',topic:1,type:'parts',source:'Física I.html:1669-1681',prompt:'Tres equipos miden un pasillo: 3.20 m, 325 cm y 3.15 m. Calcula solo el promedio de las tres mediciones en metros. Escríbelo con dos decimales.',parts:[{id:'promedio',label:'Promedio',unit:'m',answer:3.20,decimals:2}],explain:'325 cm = 3.25 m. El promedio es (3.20 + 3.25 + 3.15) / 3 = 3.20 m.'},
  {id:'m-rapidez',topic:1,type:'parts',source:'Física I.html:1331-1333,1675,1692',prompt:'Un recorrido tiene tres tramos: 1.25 km, 360 m y 24 000 cm. Calcula la distancia total y exprésala primero en metros y después en kilómetros.',parts:[{id:'metros',label:'Distancia total en metros',unit:'m',answer:1850},{id:'kilometros',label:'Distancia total en kilómetros',unit:'km',answer:1.85,decimals:2}],explain:'1.25 km = 1250 m y 24 000 cm = 240 m. La suma es 1250 + 360 + 240 = 1850 m, equivalentes a 1.85 km.'},
  {id:'m-camino',topic:1,type:'parts',source:'Física I.html:1283-1285,1704-1715',prompt:'Una persona camina 9 m al este, 4 m al oeste y 2 m al este. Calcula la distancia total y el desplazamiento. Para este último, escribe la magnitud y elige el sentido.',parts:[{id:'distancia',label:'Distancia total',unit:'m',answer:15},{id:'desplazamiento',label:'Magnitud del desplazamiento',unit:'m',answer:7},{id:'sentido',label:'Sentido del desplazamiento',kind:'choice',choices:['Este','Oeste','Sin desplazamiento','No se puede determinar'],answer:'Este'}],explain:'La distancia suma los tres tramos: 9 + 4 + 2 = 15 m. El desplazamiento toma los sentidos: 9 − 4 + 2 = 7 m al este.'},
  {id:'m-suma',topic:1,type:'parts',source:'Física I.html:1750-1766',prompt:'Suma los vectores A = (5, 2), B = (−1, 4) y C = (0, −3). Obtén las componentes de R = A + B + C y la magnitud de R.',parts:[{id:'x',label:'Componente horizontal de R',unit:'unidades',answer:4},{id:'y',label:'Componente vertical de R',unit:'unidades',answer:3},{id:'magnitud',label:'Magnitud de R',unit:'unidades',answer:5}],explain:'R = (5 − 1 + 0, 2 + 4 − 3) = (4, 3). Su magnitud es √(4² + 3²) = 5 unidades.'},
  {id:'m-resta',topic:1,type:'parts',source:'Física I.html:1770-1786',prompt:'Calcula R = A − B si A = (2, 7) y B = (6, 4). Obtén las dos componentes y la magnitud de R.',parts:[{id:'x',label:'Componente horizontal de R',unit:'unidades',answer:-4},{id:'y',label:'Componente vertical de R',unit:'unidades',answer:3},{id:'magnitud',label:'Magnitud de R',unit:'unidades',answer:5}],explain:'R = (2 − 6, 7 − 4) = (−4, 3). Su magnitud es √(16 + 9) = 5 unidades.'},
  {id:'m-ruta',topic:1,type:'choice',source:'Física I.html:1790-1805',prompt:'Un robot avanza 5 unidades al este, 2 al norte, 1 al oeste y 1 al sur. Elige la opción que indica correctamente la distancia total y el desplazamiento.',choices:['Distancia: 9 unidades. Desplazamiento: 4 unidades al este y 1 al norte.','Distancia: 9 unidades. Desplazamiento: 4 unidades al este y 2 al norte.'],answer:'Distancia: 9 unidades. Desplazamiento: 4 unidades al este y 1 al norte.',explain:'La distancia suma los cuatro tramos: 5 + 2 + 1 + 1 = 9. El desplazamiento es 4 unidades al este y 1 al norte; la otra opción omite el último tramo hacia el sur.'},
  {id:'v-referencia',topic:3,type:'choice',source:'Física I.html:2050',prompt:'Una caja permanece quieta sobre un piso horizontal cuando la empujan con 6 N hacia la derecha. El empuje aumenta a 9 N y la caja sigue quieta. Si el empuje y la fricción son las únicas fuerzas horizontales, ¿cómo cambia la fricción estática?',choices:['Aumenta de 6 N a 9 N hacia la izquierda.','Permanece en 6 N hacia la izquierda.','Aumenta de 6 N a 9 N hacia la derecha.','Permanece en 0 N porque la caja no se mueve.'],answer:'Aumenta de 6 N a 9 N hacia la izquierda.',visuals:[{friction:[6,9],direction:'left'},{friction:[6,6],direction:'left'},{friction:[6,9],direction:'right'},{friction:[0,0],direction:'none'}],explain:'Como la caja permanece quieta, la fuerza neta horizontal es cero. La fricción estática se ajusta de 6 N a 9 N, siempre hacia la izquierda, para equilibrar el empuje.'},
  {id:'v-grafica',topic:2,type:'choice',source:'Física I.html:1569-1573,1638-1644',prompt:'Observa la gráfica de posición y tiempo. ¿Qué hace el objeto entre los segundos 2 y 5?',image:{src:'assets/grafica-posicion-tiempo.svg',alt:'Gráfica con los puntos tiempo y posición: 0 s y 0 m; 2 s y 4 m; 5 s y 4 m; 7 s y 6 m.'},choices:['No cambia de posición.','Avanza 4 m.','Regresa a 0 m.','Aumenta su rapidez.'],answer:'No cambia de posición.',explain:'Entre 2 y 5 segundos la posición es de 4 m en ambos extremos y durante todo ese tramo.'},
  {id:'v-pendiente',topic:2,type:'parts',source:'Física I.html:1575-1595,1930-1944',prompt:'Un tren avanza hacia la derecha a 16 m/s. Frena de forma uniforme durante 6 s y termina con una velocidad de 4 m/s. Toma la derecha como sentido positivo. Calcula su aceleración.',formulas:[{id:'acceleration',text:'a = (vf − vi) / t'}],parts:[{id:'aceleracion',label:'Aceleración con signo',unit:'m/s²',answer:-2}],explain:'a = (4 − 16) / 6 = −2 m/s². El signo negativo indica que la aceleración apunta en sentido contrario al avance.'},
  {id:'v-tabla',topic:2,type:'parts',source:'Física I.html:1845-1857',prompt:'Un móvil mantiene una velocidad constante. Usa la tabla para calcular su velocidad y su posición a los 10 s.',table:[['Tiempo (s)','0','3','6'],['Posición (m)','2','11','20']],formulas:[{id:'tableVelocity',text:'v = (xf − xi) / (tf − ti)'},{id:'uniformPosition',text:'x = x0 + vt'}],parts:[{id:'velocidad',label:'Velocidad',unit:'m/s',answer:3},{id:'posicion',label:'Posición a los 10 s',unit:'m',answer:32}],explain:'La posición aumenta 9 m cada 3 s: v = 3 m/s. La ecuación es x = 2 + 3t; para t = 10 s, x = 32 m.'},
  {id:'v-negativa',topic:2,type:'parts',source:'Física I.html:1861-1872',prompt:'Un móvil parte de x₀ = −5 m y avanza hacia la derecha con velocidad constante de 4 m/s durante 6 s. Calcula su desplazamiento y su posición final.',formulas:[{id:'displacementSpeed',text:'Δx = vt'},{id:'finalFromDisplacement',text:'xf = x0 + Δx'}],parts:[{id:'desplazamiento',label:'Desplazamiento',unit:'m',answer:24},{id:'posicion',label:'Posición final',unit:'m',answer:19}],explain:'Δx = vt = 4 × 6 = 24 m. La posición final es x₀ + Δx = −5 + 24 = 19 m.'},
  {id:'v-tiempo',topic:2,type:'parts',source:'Física I.html:1876-1890',prompt:'Una patinadora comienza en x₀ = 3 m y avanza con velocidad constante de 3 m/s. ¿Cuánto se desplaza y cuánto tarda en llegar a x_f = 21 m?',formulas:[{id:'displacementPositions',text:'Δx = xf − x0'},{id:'timeFromDisplacement',text:'t = Δx / v'}],parts:[{id:'desplazamiento',label:'Desplazamiento',unit:'m',answer:18},{id:'tiempo',label:'Tiempo',unit:'s',answer:6}],explain:'El desplazamiento es 21 − 3 = 18 m. Con velocidad constante, t = Δx / v = 18 / 3 = 6 s.'},
  {id:'v-aceleracion',topic:2,type:'parts',source:'Física I.html:1912-1926,1948-1962',prompt:'Un carrito inicia en x₀ = 0 m, con velocidad de 2 m/s y aceleración constante de 1.5 m/s². Calcula su velocidad final y su posición después de 4 s.',formulas:[{id:'finalVelocity',text:'vf = vi + at'},{id:'acceleratedPosition',text:'xf = x0 + vit + ½at²'}],parts:[{id:'velocidad',label:'Velocidad final',unit:'m/s',answer:8},{id:'posicion',label:'Posición final',unit:'m',answer:20}],explain:'v final = 2 + 1.5 × 4 = 8 m/s. x final = 0 + 2 × 4 + ½ × 1.5 × 4² = 20 m.'},
  {id:'v-frenado',topic:2,type:'parts',source:'Física I.html:2002-2018',prompt:'Una motocicleta comienza a frenar en x₀ = 5 m, con velocidad inicial de 18 m/s y aceleración constante de −3 m/s². Calcula cuánto tarda en detenerse, qué distancia recorre durante el frenado y en qué posición termina.',formulas:[{id:'finalVelocity',text:'vf = vi + at'},{id:'acceleratedPosition',text:'xf = x0 + vit + ½at²'},{id:'distanceFinal',text:'d = xf − x0'}],parts:[{id:'tiempo',label:'Tiempo de frenado',unit:'s',answer:6},{id:'distancia',label:'Distancia de frenado',unit:'m',answer:54},{id:'posicion',label:'Posición final',unit:'m',answer:59}],explain:'Al detenerse, v final = 0. Entonces t = 6 s, d = 54 m y x final = 5 + 54 = 59 m.'},
  {id:'v-encuentro',topic:2,type:'parts',source:'Física I.html:1984-1998',prompt:'Ana y Luis están separados por 20 m. Comienzan al mismo tiempo a caminar en línea recta uno hacia el otro con velocidades constantes de 2 m/s y 3 m/s, respectivamente. ¿Qué distancia los separa después de 2 s?',formulas:[{id:'remainingDistance',text:'d = d0 − (vA + vL)t'}],parts:[{id:'distancia',label:'Distancia que los separa',unit:'m',answer:10}],explain:'Ana recorre 4 m y Luis 6 m. La separación disminuye 10 m: d = 20 − (2 + 3) × 2 = 10 m.'},
  {id:'f-primera',topic:3,type:'choice',mode:'Resolución',source:'Física I.html:2045,2060-2068',prompt:'Dos personas jalan una maleta con ruedas al mismo tiempo: una aplica 14 N hacia la derecha y la otra 9 N hacia la izquierda. Considera que son las únicas fuerzas horizontales. ¿Cuál es la fuerza neta horizontal sobre la maleta?',choices:['5 N hacia la derecha.','5 N hacia la izquierda.','23 N hacia la derecha.','0 N.'],answer:'5 N hacia la derecha.',explain:'Como las fuerzas tienen sentidos opuestos, la fuerza neta horizontal es 14 − 9 = 5 N hacia la derecha.'},
  {id:'f-tercera',topic:3,type:'choice',source:'Física I.html:2047-2048,2104-2113',prompt:'Una cuerda eleva una cubeta. La cuerda jala la cubeta hacia arriba, mientras la Tierra la atrae hacia abajo. ¿Qué fuerza ejerce la cubeta sobre la cuerda?',choices:['La cubeta jala la cuerda hacia abajo.','La Tierra jala la cubeta hacia abajo.','La cubeta jala la Tierra hacia arriba.','La cuerda jala la cubeta hacia arriba.'],answer:'La cubeta jala la cuerda hacia abajo.',explain:'La cuerda jala la cubeta hacia arriba y la cubeta jala la cuerda hacia abajo. Las fuerzas tienen igual magnitud y actúan sobre cuerpos distintos.'},
  {id:'f-friccion',topic:3,type:'choice',source:'Física I.html:2050',prompt:'Una caja sigue quieta aunque una persona la empuja horizontalmente. El empuje aún no supera el límite de fricción estática. ¿Qué ocurre con la fricción?',choices:['Se ajusta para igualar el empuje','Siempre toma su valor máximo','Se vuelve cero porque la caja no se mueve','Apunta en el mismo sentido que el empuje'],answer:'Se ajusta para igualar el empuje',explain:'Mientras la caja no desliza y no se alcanza el límite, la fricción estática equilibra el empuje horizontal.'},
  {id:'f-empujes',topic:3,type:'parts',source:'Física I.html:2060-2068',prompt:'Sobre una caja de 6 kg actúan 25 N hacia la derecha, 9 N hacia la izquierda y 4 N hacia la izquierda. Son las únicas fuerzas horizontales. Calcula la fuerza neta y la aceleración horizontales.',parts:[{id:'fuerza',label:'Magnitud de la fuerza neta',unit:'N',answer:12},{id:'aceleracion',label:'Magnitud de la aceleración',unit:'m/s²',answer:2},{id:'sentido',label:'Sentido de ambas',kind:'choice',choices:['Derecha','Izquierda','No hay aceleración','No puede determinarse'],answer:'Derecha'}],explain:'La fuerza neta es 25 − 9 − 4 = 12 N hacia la derecha. Por la segunda ley, a = 12 / 6 = 2 m/s² hacia la derecha.'},
  {id:'f-pelota',topic:3,type:'parts',source:'Física I.html:2071-2079',prompt:'Una pelota de 0.8 kg acelera horizontalmente a 5 m/s² hacia la derecha durante un empuje. Calcula su fuerza neta horizontal y elige su sentido.',parts:[{id:'fuerza',label:'Magnitud de la fuerza neta',unit:'N',answer:4},{id:'sentido',label:'Sentido de la fuerza neta',kind:'choice',choices:['Derecha','Izquierda','No hay fuerza neta','Perpendicular al movimiento'],answer:'Derecha'}],explain:'Fuerza neta = ma = 0.8 × 5 = 4 N. La fuerza neta tiene el mismo sentido que la aceleración.'},
  {id:'f-frenado',topic:3,type:'parts',source:'Física I.html:2082-2090',prompt:'Un pasajero de 50 kg reduce su velocidad de 8 m/s a cero en 4 s, con frenado uniforme. Toma el sentido inicial como positivo. Calcula su aceleración y la fuerza neta horizontal con signo.',parts:[{id:'aceleracion',label:'Aceleración con signo',unit:'m/s²',answer:-2},{id:'fuerza',label:'Fuerza neta con signo',unit:'N',answer:-100}],explain:'a = (0 − 8) / 4 = −2 m/s². La fuerza neta es 50 × (−2) = −100 N; se opone al movimiento inicial.'},
  {id:'f-mochila',topic:3,type:'parts',source:'Física I.html:2093-2101',prompt:'Una mochila de 7 kg reposa sobre una mesa horizontal. Solo actúan peso y fuerza normal en vertical. Usa g = 10 m/s² y calcula la magnitud de ambas fuerzas.',parts:[{id:'peso',label:'Peso',unit:'N',answer:70},{id:'normal',label:'Fuerza normal',unit:'N',answer:70}],explain:'Peso = mg = 7 × 10 = 70 N hacia abajo. Como no hay aceleración vertical, la normal es 70 N hacia arriba.'},
  {id:'f-cubeta',topic:3,type:'parts',source:'Física I.html:2104-2113',prompt:'Una cuerda eleva verticalmente una cubeta de 3 kg con aceleración de 2 m/s² hacia arriba. Solo actúan tensión y peso sobre la cubeta. Usa g = 10 m/s². Calcula el peso, la tensión y la magnitud de la fuerza de la cubeta sobre la cuerda.',parts:[{id:'peso',label:'Peso de la cubeta',unit:'N',answer:30},{id:'tension',label:'Tensión de la cuerda',unit:'N',answer:36},{id:'reaccion',label:'Fuerza de la cubeta sobre la cuerda',unit:'N',answer:36}],explain:'Peso = 3 × 10 = 30 N. Como tensión − peso = ma, la tensión es 30 + 3 × 2 = 36 N. La cubeta jala la cuerda con 36 N hacia abajo.'},
  {id:'f-cubeta-inversa',topic:3,type:'parts',source:'Física I.html:2047-2048,2104-2113',prompt:'Una cuerda tira hacia arriba de una cubeta de 5 kg con tensión de 60 N. Solo actúan tensión y peso. Usa g = 10 m/s². Calcula el peso, la fuerza neta y la aceleración; indica el sentido de esta última.',parts:[{id:'peso',label:'Peso',unit:'N',answer:50},{id:'fuerza',label:'Magnitud de la fuerza neta',unit:'N',answer:10},{id:'aceleracion',label:'Magnitud de la aceleración',unit:'m/s²',answer:2},{id:'sentido',label:'Sentido de la aceleración',kind:'choice',choices:['Arriba','Abajo','No acelera','No puede determinarse'],answer:'Arriba'}],explain:'Peso = 5 × 10 = 50 N. La fuerza neta es 60 − 50 = 10 N hacia arriba y a = 10 / 5 = 2 m/s² hacia arriba.'}
];

/* Cada intento conserva el banco con el que comenzó, incluso tras una actualización. */
const V3_OVERRIDES = {
  'v-negativa': {prompt:'Un móvil parte de x₀ = −5 m y avanza hacia la derecha a 4 m/s durante 6 s. Calcula su desplazamiento y su posición final.'},
  'v-encuentro': {prompt:'Ana sale de x = 0 m y avanza a 2 m/s. Luis sale al mismo tiempo de x = 20 m y avanza hacia Ana a 3 m/s. Calcula el instante y la posición de encuentro.',formulas:null,parts:[{id:'tiempo',label:'Tiempo hasta el encuentro',unit:'s',answer:4},{id:'posicion',label:'Posición de encuentro desde el origen de Ana',unit:'m',answer:8}],explain:'Sus posiciones son x de Ana = 2t y x de Luis = 20 − 3t. Al igualarlas, 5t = 20, t = 4 s y x = 8 m.'},
  'f-tercera': {prompt:'Una cuerda jala una cubeta hacia arriba. ¿Cuál es la fuerza que forma el par de interacción con ese jalón?',choices:['La fuerza de la cubeta sobre la cuerda hacia abajo','El peso de la cubeta hacia abajo','La fuerza del piso sobre la persona que sostiene la cuerda','La tensión de la cuerda sobre la cubeta hacia abajo'],answer:'La fuerza de la cubeta sobre la cuerda hacia abajo',explain:'En la tercera ley, las fuerzas son iguales en magnitud y opuestas en sentido, pero actúan sobre cuerpos distintos: cuerda y cubeta.'}
};
window.V3_QUESTIONS = window.QUESTIONS.map(question=>({...question,...(V3_OVERRIDES[question.id]||{})}));
const V2_OVERRIDES = {
  'v-grafica': {prompt:'En una gráfica de posición contra tiempo, la línea permanece horizontal entre los segundos 2 y 5. ¿Qué ocurre con el objeto en ese intervalo?',image:null,choices:['Permanece en reposo respecto al eje elegido','Se mueve con velocidad constante distinta de cero','Aumenta su velocidad de forma uniforme','Regresa hacia el origen'],answer:'Permanece en reposo respecto al eje elegido',explain:'Una línea horizontal indica posición constante durante ese intervalo; no informa que la posición sea cero.'},
  'v-pendiente': {type:'choice',source:'Física I.html:1575-1595',prompt:'En una gráfica de velocidad contra tiempo, ¿qué magnitud representa la pendiente?',formulas:null,parts:null,choices:['Aceleración','Desplazamiento','Posición inicial','Rapidez promedio'],answer:'Aceleración',explain:'La pendiente de velocidad contra tiempo expresa cuánto cambia la velocidad por unidad de tiempo.'},
  'v-tabla': {prompt:'Una tabla posición-tiempo muestra x = 2 m en t = 0 s, x = 11 m en t = 3 s y x = 20 m en t = 6 s. Si el patrón continúa, calcula la velocidad constante y la posición en t = 10 s.',table:null,formulas:null},
  'v-negativa': {prompt:'Un móvil parte de x₀ = −5 m y se desplaza a velocidad constante de 4 m/s hacia la derecha durante 6 s. Calcula el desplazamiento y la posición final.',formulas:null},
  'v-tiempo': {prompt:'Una patinadora comienza en x₀ = 3 m y avanza a 3 m/s. ¿Cuánto se desplaza y cuánto tarda en llegar a x = 21 m?',formulas:null},
  'v-aceleracion': {prompt:'Un carrito inicia en x₀ = 0 m con velocidad de 2 m/s y aceleración constante de 1.5 m/s². Calcula su velocidad final y posición después de 4 s.',formulas:null},
  'v-frenado': {prompt:'Una motocicleta empieza a frenar en x₀ = 5 m con velocidad de 18 m/s y aceleración constante de −3 m/s² hasta detenerse. Calcula tiempo de frenado, distancia recorrida durante el frenado y posición final.',formulas:null,explain:'0 = 18 − 3t da t = 6 s. El avance es 18 × 6 − ½ × 3 × 6² = 54 m; x final = 5 + 54 = 59 m.'},
  'f-primera': {source:'Física I.html:2037-2049',prompt:'Un carrito se mueve en línea recta con velocidad constante. ¿Cuánto vale la suma de las fuerzas que actúan sobre él?',mode:null,choices:['0 N','Una fuerza igual a su peso','Una fuerza en el sentido del movimiento','No puede recibir ninguna fuerza'],answer:'0 N',explain:'La primera ley establece que la fuerza neta es cero si un cuerpo mantiene velocidad constante en línea recta.'}
};
window.V2_QUESTIONS = window.V3_QUESTIONS.map(question=>({...question,...(V2_OVERRIDES[question.id]||{})}));
const LEGACY_OVERRIDES = {
  'm-sentido': {prompt:'Dos fuerzas de 15 N actúan sobre una caja: una apunta al este y otra al oeste. ¿Qué característica vectorial permite diferenciarlas?',choices:['Su sentido','Su magnitud','Su unidad','Su dirección horizontal'],answer:'Su sentido',explain:'Ambas tienen igual magnitud, unidad y dirección horizontal. Cambia el sentido sobre esa dirección.'},
  'm-precision': {type:'choice',prompt:'Una báscula marca 2 kg de más cada vez que se pesa el mismo objeto. Sus resultados son muy parecidos entre sí. ¿Cómo se describen esas mediciones?',choices:['Precisas, pero no exactas','Exactas, pero no precisas','Precisas y exactas','Ni precisas ni exactas'],answer:'Precisas, pero no exactas',explain:'La repetición cercana indica precisión; el error constante respecto del valor real impide llamarlas exactas.'},
  'm-promedio': {prompt:'Tres equipos miden un pasillo: 3.20 m, 325 cm y 3.15 m. Calcula el promedio y el rango de las tres medidas. Escribe ambos con dos decimales.',parts:[{id:'promedio',label:'Promedio',unit:'m',answer:3.20,decimals:2},{id:'rango',label:'Rango',unit:'m',answer:0.10,decimals:2}],explain:'325 cm = 3.25 m. El promedio es (3.20 + 3.25 + 3.15) / 3 = 3.20 m; el rango es 3.25 − 3.15 = 0.10 m.'},
  'm-rapidez': {prompt:'Una bicicleta mantiene 54 km/h durante 32 s. Convierte la rapidez a m/s y calcula la distancia recorrida.',parts:[{id:'rapidez',label:'Rapidez',unit:'m/s',answer:15},{id:'distancia',label:'Distancia',unit:'m',answer:480}],explain:'54 km/h ÷ 3.6 = 15 m/s. Con rapidez constante, d = vt = 15 × 32 = 480 m.'},
  'm-ruta': {type:'parts',prompt:'Un robot avanza 5 unidades al este, 2 al norte, 1 al oeste y 1 al sur. Calcula la distancia, las componentes del desplazamiento y su magnitud. Redondea esta última a dos decimales.',parts:[{id:'distancia',label:'Distancia total',unit:'unidades',answer:9},{id:'x',label:'Desplazamiento horizontal',unit:'unidades',answer:4},{id:'y',label:'Desplazamiento vertical',unit:'unidades',answer:1},{id:'magnitud',label:'Magnitud del desplazamiento',unit:'unidades',answer:4.12,decimals:2}],explain:'La distancia es 5 + 2 + 1 + 1 = 9. El desplazamiento es (5 − 1, 2 − 1) = (4, 1), cuya magnitud es √17 ≈ 4.12.'},
  'v-referencia': {topic:2,source:'Física I.html:1411-1415,1425-1433',prompt:'Una alumna permanece sentada en un autobús que avanza. ¿Qué descripción del movimiento es correcta?',choices:['Está en reposo respecto al asiento y en movimiento respecto a la calle','Está en movimiento respecto al asiento y en reposo respecto a la calle','Está en reposo respecto al asiento y a la calle','Está en movimiento respecto al asiento y a la calle'],answer:'Está en reposo respecto al asiento y en movimiento respecto a la calle',visuals:null,explain:'El movimiento depende del sistema de referencia. La alumna no cambia de posición frente al asiento, pero sí frente a la calle.'}
};
window.LEGACY_QUESTIONS = window.V2_QUESTIONS.map(question=>({...question,...(LEGACY_OVERRIDES[question.id]||{})}));
/* Los resultados actuales son exactos; las versiones previas conservan su tolerancia. */
window.QUESTIONS = window.QUESTIONS.map(question=>({...question,...(question.type==='parts'?{parts:question.parts.map(part=>part.kind==='choice'?part:{...part,exact:true})}:{})}));
